import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../app/globals.css";
import Header from "@/components/Nabvar/Header";
import { ToastContainer } from "react-toastify";
import ReactQueryClientProvider from "@/provider/quertClient";
import TeamAndFooterCard from "@/components/Nabvar/about";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Always use a static value for username here to avoid hydration mismatch
  const username = ""; // Don't use client-only logic here

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased pt-[100px]`}
      >
        <Header username={username} />
        <ReactQueryClientProvider>{children}</ReactQueryClientProvider>
        <ToastContainer position="top-right" autoClose={3000} />
      </body>
    </html>
  );
}
